### ISSUE TITLE
Mobile App UI/UX

### ISSUE THREAD

**Issue by FrozenWolf-Cyber** [FrozenWolf-Cyber/SIH#4]
Need to make better UI design, in order to make the app modern.
- [ ] Change Buttons
- [ ] Change font faces
- [ ] Change images
- [ ] Change App icon
- [ ] Change colour palette

UI Mockups:
https://app.visily.ai/projects/1fe69504-3cba-4b26-8829-020a1c32eed7/boards/191680

**Comment by aadarsh-ram** [comment]
Done
